### PR TITLE
add source maps and explicit options for bare and const

### PR DESCRIPTION
**Pull request by hzamani**

### CODE REVIEW

**Comment by vendethiel** [comment]
:+1:

**Comment by es128** [comment]
Cool, thanks. Can you add some readme documentation explaining the new options?

**Comment by hzamani** [comment]
Any comment?

**Comment by es128** [comment]
Sorry, hadn't seen that this PR was updated because GH doesn't send notifications about new commits. 

Looks good, but am on mobile now and will take a closer look when I get back to a computer. 

Feel free to ping again if you don't hear back soon.

**Pull request merged**
